### ISSUE TITLE
TODO-s

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/tiny-cache#3]
- [ ] Document mu-cache-flush-button mu-cache-flush-on-maintenance mu-cache-flush-post-button
- [ ] Support groups: wp_cache_add_global_groups( 'the_content' ); and WP_REDIS_USE_CACHE_GROUPS
- [ ] Add $more_link_text and $strip_teaser hash to cache key
